name: Build Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build plugin
        run: ./gradlew build

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: DinoStreaming.cs3
          path: build/libs/*.cs3

      - name: Deploy to builds branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/libs
          publish_branch: builds
          destination_dir: .
