name: Check repos

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Run checks
        run: |
          python3 ci_check.py
      - name: Update Rentry
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) # Only runs if this CI was triggered by the default branch
        run: |
          python3 -m pip install rentry
          cat list.md | rentry edit -p ${{ secrets.RENTRY_PW }} -u cs3-repos
